"""
Django settings for home_services project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y045fyx-zr6zc)n4ss0hh(45)i2yxw#@&hqj&&-ntcj%)x-fyu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Allow all hosts for development

# Make sure HTTPS is not enforced
SECURE_SSL_REDIRECT = False
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_CONTENT_TYPE_NOSNIFF = False
SECURE_BROWSER_XSS_FILTER = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# Application definition

INSTALLED_APPS = [
    'daphne',  # Daphne must be first for Channels support
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth
    'rest_framework',  # Django REST Framework
    'rest_framework.authtoken',  # Token authentication
    'corsheaders',  # CORS headers
    'channels',  # Django Channels for WebSocket support
    'allauth',  # Django allauth
    'allauth.account',  # Allauth account management
    'allauth.socialaccount',  # Social account support
    'allauth.socialaccount.providers.google',  # Google OAuth
    'allauth.socialaccount.providers.facebook',  # Facebook OAuth
    'allauth.socialaccount.providers.microsoft',  # Microsoft OAuth
    'services',  # Our main app
    'analytics',  # Analytics app
]

SITE_ID = 1

MIDDLEWARE = [
    # ============================================================================
    # MIDDLEWARE ORDER - CRITICAL FOR PROPER FUNCTIONALITY
    # ============================================================================
    # The order of middleware is important. Each middleware processes requests
    # from top to bottom and responses from bottom to top.
    #
    # Order rationale:
    # 1. Security - First line of defense
    # 2. CORS - Must be before CommonMiddleware
    # 3. Sessions - Required for authentication
    # 4. Authentication - Required for user identification
    # 5. Rate Limiting - Protect against abuse (before cache)
    # 6. API Versioning - Route to correct API version
    # 7. Mobile Optimization - Detect and optimize for mobile
    # 8. Metrics Collection - Track all requests
    # 9. Cache Headers - Set cache policies
    # 10. CDN Integration - CDN cache and performance
    # 11. Compression - Last, to compress final response
    # ============================================================================
    
    # Security and CORS (must be first)
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware (must be before CommonMiddleware)
    
    # Session and authentication
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Internationalization
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Allauth middleware
    
    # Rate limiting (Requirements: 4.1-4.5) - MUST come before cache
    'services.middleware.rate_limit_middleware.RateLimitMiddleware',
    
    # API versioning (Requirements: 12.1, 12.5)
    'services.api.versioning.APIVersionMiddleware',
    
    # Mobile optimization (Requirements: 10.1-10.5)
    'services.middleware.mobile_optimization_middleware.MobileOptimizationMiddleware',
    
    # Metrics collection (Requirements: 6.1-6.5)
    'services.middleware.metrics_middleware.MetricsMiddleware',
    
    # Custom business logic
    'services.middleware.LoginRequiredMiddleware',
    'services.ai_middleware.AIAnalyticsMiddleware',
    'services.profile_middleware.ProfileTrackingMiddleware',
    
    # Cache management (Requirements: 1.1-1.5)
    'services.middleware.cache_middleware.CacheHeaderMiddleware',
    'services.middleware.cdn_cache_middleware.CDNCacheMiddleware',
    'services.middleware.cdn_cache_middleware.CacheInvalidationMiddleware',
    'services.middleware.cdn_cache_middleware.CDNPerformanceMiddleware',
    
    # Compression (Requirements: 5.1-5.5) - MUST be last to compress final response
    'services.middleware.compression_middleware.BrotliMiddleware',  # Brotli (preferred)
    'django.middleware.gzip.GZipMiddleware',  # GZip (fallback)
]

ROOT_URLCONF = 'home_services.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', BASE_DIR / 'templates/admin'],  # Add templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'services.context_processors.global_context',
                'services.ai_context_processor.ai_insights',
            ],
        },
    },
]

WSGI_APPLICATION = 'home_services.wsgi.application'
ASGI_APPLICATION = 'home_services.asgi.application'

# ============================================================================
# REDIS CONFIGURATION
# ============================================================================
# Requirements: 8.1 (scalability), 8.2 (caching)

# Redis connection settings
REDIS_HOST = os.environ.get('REDIS_HOST', '127.0.0.1')
REDIS_PORT = int(os.environ.get('REDIS_PORT', 6379))
REDIS_DB = int(os.environ.get('REDIS_DB', 0))

# Use Redis for production, in-memory for development without Redis
USE_REDIS = os.environ.get('USE_REDIS', 'False').lower() == 'true'

# ============================================================================
# CHANNEL LAYERS CONFIGURATION (Django Channels)
# ============================================================================
# Requirements: 8.1 (support 100+ concurrent sessions)

if USE_REDIS:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [(REDIS_HOST, REDIS_PORT)],
                # Capacity: Maximum number of messages in a channel before blocking
                # Requirement 8.1: Support 100+ concurrent sessions
                'capacity': int(os.environ.get('CHANNEL_CAPACITY', '1500')),
                # Expiry: How long messages stay in channel before being discarded (seconds)
                'expiry': int(os.environ.get('CHANNEL_EXPIRY', '10')),
                # Group expiry: How long channel groups persist (seconds)
                # Set to 24 hours to match chat session timeout
                'group_expiry': int(os.environ.get('CHANNEL_GROUP_EXPIRY', '86400')),
                # Connection pool settings for better performance
                'connection_pool_kwargs': {
                    'max_connections': 100,
                    'retry_on_timeout': True,
                },
                # Symmetric encryption for messages (optional, for security)
                'symmetric_encryption_keys': [SECRET_KEY],
            },
        },
    }
else:
    # For development without Redis
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
            'CONFIG': {
                'capacity': 100,  # Lower capacity for in-memory
                'expiry': 10,
            }
        }
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'  # Changed to Portuguese

TIME_ZONE = 'America/Sao_Paulo'  # Changed to São Paulo timezone

USE_I18N = True

USE_TZ = True

# Internationalization settings
LANGUAGES = [
    ('pt-br', 'Português (Brasil)'),
    ('en', 'English'),
    ('es', 'Español'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# ============================================================================
# CDN CONFIGURATION
# ============================================================================

# CDN Settings
# Requirement 9.1: Serve all static files through CDN
CDN_ENABLED = os.environ.get('CDN_ENABLED', 'False').lower() == 'true'
CDN_URL = os.environ.get('CDN_URL', '')  # e.g., 'https://cdn.example.com'
CDN_STATIC_PATH = '/static/'
CDN_MEDIA_PATH = '/media/'

# Image Optimization Settings
# Requirement 9.3: Optimize images automatically for different devices
CDN_OPTIMIZE_IMAGES = True

# Modern Image Format Support
# Requirement 9.4: Support WebP and AVIF formats
CDN_WEBP_ENABLED = True
CDN_AVIF_ENABLED = False  # Enable when pillow-avif-plugin is installed

# Static files configuration
STATIC_URL = f"{CDN_URL}{CDN_STATIC_PATH}" if CDN_ENABLED else '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Storage backends for CDN
if CDN_ENABLED:
    STATICFILES_STORAGE = 'services.storage_backends.CDNStaticStorage'
    DEFAULT_FILE_STORAGE = 'services.storage_backends.CDNMediaStorage'

# Media files (User uploaded files)
MEDIA_URL = f"{CDN_URL}{CDN_MEDIA_PATH}" if CDN_ENABLED else '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email configuration for password reset
# For development, we'll use the console backend to print emails to the console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production, you would use something like:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.your-email-provider.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@your-domain.com'
# EMAIL_HOST_PASSWORD = 'your-email-password'

# Login settings
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_REDIRECT_URL = 'home'

# Custom error pages
handler404 = 'services.views.custom_404'
handler500 = 'services.views.custom_500'
handler403 = 'services.views.custom_403'
handler400 = 'services.views.custom_400'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'services': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Stripe settings (for payment processing)
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')

# Email settings
DEFAULT_FROM_EMAIL = 'noreply@jobfinder.com'

# ============================================================================
# CACHING CONFIGURATION
# ============================================================================
# Requirements: 8.1 (scalability), 8.2 (response caching)

# Cache timeouts for different data types (in seconds)
CACHE_TIMEOUT = 60 * 15  # 15 minutes (default)
CACHE_TIMEOUT_LISTINGS = 60 * 15  # 15 minutes for service/professional listings
CACHE_TIMEOUT_DETAILS = 60 * 30  # 30 minutes for detail pages
CACHE_TIMEOUT_USER = 60 * 5  # 5 minutes for user-specific data
CACHE_TIMEOUT_SEARCH = 60 * 10  # 10 minutes for search results

# Cache key prefixes for organization
CACHE_KEY_PREFIX = 'homeservices'

# Caching Configuration
# Using Redis for production, LocMem for development without Redis
if USE_REDIS:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/1',
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 50,
                    'retry_on_timeout': True,
                },
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
            },
            'KEY_PREFIX': CACHE_KEY_PREFIX,
            'TIMEOUT': CACHE_TIMEOUT,
        },
        # Separate cache for chat responses (Requirement 8.2)
        'chat': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/2',
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 30,
                    'retry_on_timeout': True,
                },
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
            },
            'KEY_PREFIX': 'chat',
            'TIMEOUT': 3600,  # 1 hour for chat responses
        }
    }
else:
    # For development without Redis
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-jobfinder-cache',
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
                'CULL_FREQUENCY': 3,
            }
        },
        'chat': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'chat-cache',
            'OPTIONS': {
                'MAX_ENTRIES': 500,
                'CULL_FREQUENCY': 3,
            }
        }
    }

# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Django Allauth Configuration
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default backend
    'allauth.account.auth_backends.AuthenticationBackend',  # Allauth backend
]

# Allauth settings (updated for latest version)
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_ADAPTER = 'services.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'services.adapters.CustomSocialAccountAdapter'
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_STORE_TOKENS = True

# Social account providers settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
        ],
        'EXCHANGE_TOKEN': True,
        'VERIFIED_EMAIL': False,
        'VERSION': 'v18.0'
    },
    'microsoft': {
        'SCOPE': [
            'User.Read',
            'email',
            'profile',
        ]
    }
}

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'services.api.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    },
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ============================================================================
# WEBSOCKET SECURITY CONFIGURATION (Chat IA Assistente)
# ============================================================================
# Requirements: 8.3 (Security)
# This section configures comprehensive security for WebSocket connections
# including CORS, message size limits, input validation, and rate limiting.

# WebSocket CORS Configuration
# Requirements: 8.3 - Configure CORS for WebSocket connections
# Allow WebSocket connections from the same origins as HTTP
ALLOWED_WEBSOCKET_ORIGINS = CORS_ALLOWED_ORIGINS + [
    # Add production domains here when deploying
    # "https://yourdomain.com",
    # "https://www.yourdomain.com",
    # "wss://yourdomain.com",
    # "wss://www.yourdomain.com",
]

# WebSocket CORS Headers
# Requirements: 8.3 - Configure CORS for WebSocket connections
# These headers are allowed in WebSocket upgrade requests
WEBSOCKET_CORS_ALLOWED_HEADERS = [
    'authorization',
    'content-type',
    'x-csrftoken',
    'x-requested-with',
    'sec-websocket-protocol',
    'sec-websocket-version',
    'sec-websocket-key',
    'sec-websocket-extensions',
    'origin',
    'host',
]

# WebSocket Security Settings
# Requirements: 8.3 - Set message size limits and input validation rules
# Comprehensive security configuration for WebSocket connections
WEBSOCKET_SECURITY = {
    # ========================================================================
    # ORIGIN VALIDATION (Requirements: 8.3 - Configure CORS)
    # ========================================================================
    # Enforce strict origin checking to prevent unauthorized connections
    'ENFORCE_ORIGIN_CHECK': True,
    'ALLOW_WILDCARD_ORIGIN': False,  # Set to True only for development
    'ALLOWED_ORIGINS': ALLOWED_WEBSOCKET_ORIGINS,
    
    # ========================================================================
    # CONNECTION LIMITS (Requirements: 8.3)
    # ========================================================================
    # Prevent abuse by limiting concurrent connections per user/IP
    'MAX_CONNECTIONS_PER_USER': 5,  # Maximum concurrent connections per user
    'MAX_CONNECTIONS_PER_IP': 10,  # Maximum concurrent connections per IP
    'TRACK_CONNECTIONS': True,  # Track active connections for limit enforcement
    
    # ========================================================================
    # MESSAGE SIZE LIMITS (Requirements: 8.3 - Set message size limits)
    # ========================================================================
    # Prevent DoS attacks via large messages
    'MAX_MESSAGE_SIZE': 2000,  # Maximum message content size in characters
    'MAX_FRAME_SIZE': 65536,  # Maximum WebSocket frame size in bytes (64KB)
    'ENFORCE_MESSAGE_SIZE': True,  # Enforce message size limits
    'MAX_FEEDBACK_LENGTH': 1000,  # Maximum feedback text length
    'MAX_CONTEXT_SIZE_BYTES': 10000,  # Maximum context data size (10KB)
    
    # ========================================================================
    # TIMEOUT SETTINGS (Requirements: 8.3)
    # ========================================================================
    # Prevent resource exhaustion from idle connections
    'CONNECTION_TIMEOUT': 300,  # Connection timeout in seconds (5 minutes)
    'PING_INTERVAL': 30,  # Ping interval in seconds
    'PING_TIMEOUT': 10,  # Ping timeout in seconds
    'IDLE_TIMEOUT': 600,  # Idle timeout in seconds (10 minutes)
    
    # ========================================================================
    # AUTHENTICATION & SESSION (Requirements: 8.3)
    # ========================================================================
    # Control authentication requirements
    'REQUIRE_AUTHENTICATION': False,  # Allow anonymous users
    'VALIDATE_SESSION': True,  # Validate Django session
    'VALIDATE_CSRF': False,  # CSRF validation for WebSocket (not applicable)
    
    # ========================================================================
    # INPUT VALIDATION (Requirements: 8.3 - Add input validation rules)
    # ========================================================================
    # Comprehensive input validation to prevent injection attacks
    'VALIDATE_JSON': True,  # Validate JSON format
    'VALIDATE_MESSAGE_TYPE': True,  # Validate message type
    'VALIDATE_CONTENT': True,  # Validate message content
    'BLOCK_DANGEROUS_PATTERNS': True,  # Block dangerous patterns (XSS, injection)
    'SANITIZE_INPUT': True,  # Sanitize user input (HTML escape)
    'VALIDATE_SESSION_ID': True,  # Validate session ID format (UUID)
    'VALIDATE_RATING': True,  # Validate satisfaction rating (1-5)
    'VALIDATE_CONTEXT': True,  # Validate context data structure
    
    # ========================================================================
    # RATE LIMITING (Requirements: 8.3)
    # ========================================================================
    # Prevent spam and abuse
    'ENABLE_RATE_LIMITING': True,
    'RATE_LIMIT_MESSAGES_PER_MINUTE': 10,
    'RATE_LIMIT_WINDOW_SECONDS': 60,
    'RATE_LIMIT_BURST_ALLOWANCE': 3,  # Allow burst of 3 extra messages
    
    # ========================================================================
    # LOGGING & MONITORING (Requirements: 8.3)
    # ========================================================================
    # Track security events for monitoring and debugging
    'LOG_SECURITY_EVENTS': True,
    'LOG_REJECTED_CONNECTIONS': True,
    'LOG_VALIDATION_FAILURES': True,
    'LOG_RATE_LIMIT_VIOLATIONS': True,
    'LOG_SUSPICIOUS_ACTIVITY': True,
}

# Security Headers Configuration
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# Content Security Policy for WebSocket
# Requirements: 8.3 - Additional security headers
CSP_CONNECT_SRC = ["'self'"] + [
    origin.replace('http://', 'ws://').replace('https://', 'wss://')
    for origin in ALLOWED_WEBSOCKET_ORIGINS
]

# API Rate Limiting
API_RATE_LIMIT_PER_HOUR = 1000
API_RATE_LIMIT_ANON_PER_HOUR = 100

# ============================================================================
# CHAT IA ASSISTENTE (SOPHIE) CONFIGURATION
# ============================================================================

# OpenAI Configuration
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')

# Chat Configuration
# Requirements: 8.2 (caching), 8.3 (rate limiting), 8.4 (performance)
CHAT_CONFIG = {
    # OpenAI API Configuration
    'OPENAI_API_KEY': OPENAI_API_KEY,
    'OPENAI_MODEL': os.environ.get('OPENAI_MODEL', 'gpt-4'),
    'OPENAI_TEMPERATURE': float(os.environ.get('OPENAI_TEMPERATURE', '0.7')),
    'OPENAI_MAX_TOKENS': int(os.environ.get('OPENAI_MAX_TOKENS', '500')),
    
    # Session Management
    'MAX_HISTORY_MESSAGES': int(os.environ.get('CHAT_MAX_HISTORY', '50')),
    'SESSION_TIMEOUT_HOURS': int(os.environ.get('CHAT_SESSION_TIMEOUT', '24')),
    'SESSION_CLEANUP_INTERVAL_HOURS': int(os.environ.get('CHAT_CLEANUP_INTERVAL', '6')),
    
    # Rate Limiting (Requirement 8.3)
    'RATE_LIMIT_MESSAGES_PER_MINUTE': int(os.environ.get('CHAT_RATE_LIMIT', '10')),
    'RATE_LIMIT_WINDOW_SECONDS': 60,
    'RATE_LIMIT_BURST_ALLOWANCE': 3,  # Allow burst of 3 extra messages
    
    # Caching (Requirement 8.2)
    'CACHE_TTL_SECONDS': int(os.environ.get('CHAT_CACHE_TTL', '3600')),  # 1 hour
    'CACHE_ENABLED': os.environ.get('CHAT_CACHE_ENABLED', 'True').lower() == 'true',
    'CACHE_KEY_PREFIX': 'chat_response',
    
    # Performance (Requirement 8.4)
    'MAX_CONCURRENT_SESSIONS': int(os.environ.get('CHAT_MAX_SESSIONS', '100')),
    'RESPONSE_TIMEOUT_SECONDS': int(os.environ.get('CHAT_TIMEOUT', '30')),
    'CONNECTION_TIMEOUT_SECONDS': int(os.environ.get('CHAT_CONN_TIMEOUT', '10')),
    'MAX_RETRIES': int(os.environ.get('CHAT_MAX_RETRIES', '3')),
    
    # Features
    'ENABLE_ANALYTICS': os.environ.get('CHAT_ANALYTICS', 'True').lower() == 'true',
    'FALLBACK_RESPONSES': os.environ.get('CHAT_FALLBACK', 'True').lower() == 'true',
    'ENABLE_TYPING_INDICATOR': os.environ.get('CHAT_TYPING_INDICATOR', 'True').lower() == 'true',
    
    # Security (Requirements: 8.3)
    'MAX_MESSAGE_LENGTH': int(os.environ.get('CHAT_MAX_MSG_LENGTH', '2000')),
    'MIN_MESSAGE_LENGTH': int(os.environ.get('CHAT_MIN_MSG_LENGTH', '1')),
    'MAX_FEEDBACK_LENGTH': int(os.environ.get('CHAT_MAX_FEEDBACK_LENGTH', '1000')),
    'ALLOWED_MESSAGE_TYPES': ['text', 'system'],
    'SANITIZE_INPUT': True,
    'VALIDATE_SESSION': True,
    'VALIDATE_ORIGIN': True,
    'BLOCK_DANGEROUS_PATTERNS': True,
    'HTML_ESCAPE_MESSAGES': True,
    'MAX_CONTEXT_SIZE_BYTES': int(os.environ.get('CHAT_MAX_CONTEXT_SIZE', '10000')),  # 10KB
    
    # Logging
    'LOG_LEVEL': os.environ.get('CHAT_LOG_LEVEL', 'INFO'),
    'LOG_ALL_MESSAGES': os.environ.get('CHAT_LOG_MESSAGES', 'True').lower() == 'true',
    'LOG_AI_RESPONSES': os.environ.get('CHAT_LOG_AI', 'True').lower() == 'true',
}



# ============================================================================
# COMPRESSION CONFIGURATION
# ============================================================================

# GZip Compression Settings
# Requirement 5.1: Compress responses larger than 1KB using gzip
GZIP_COMPRESSION_LEVEL = 6  # Compression level (1-9, where 9 is maximum)

# Brotli Compression Settings
# Requirement 5.2: Use brotli when client supports it
BROTLI_COMPRESSION_LEVEL = 5  # Compression level (0-11, where 11 is maximum)

# Minimum size for compression
# Requirement 5.3: Define minimum size for compression (1KB)
MIN_COMPRESSION_SIZE = 1024  # 1KB in bytes

# Compressible MIME types
# Requirement 5.5: Compress only specific MIME types
COMPRESSIBLE_MIME_TYPES = [
    'text/html',
    'text/css',
    'text/plain',
    'text/xml',
    'text/javascript',
    'application/json',
    'application/javascript',
    'application/xml',
    'application/xhtml+xml',
    'application/rss+xml',
    'application/atom+xml',
    'image/svg+xml',
]

# Compression ratio threshold
# Requirement 5.4: Validate compression ratio > 60%
MIN_COMPRESSION_RATIO = 60  # Minimum compression ratio percentage

# Content-Encoding header
# Requirement 5.3: Add Content-Encoding header indicating compression type
# This is handled automatically by the middleware
