[build]
builder = "nixpacks"

[deploy]
startCommand = "daphne home_services.asgi:application --port $PORT --bind 0.0.0.0 -v2"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10