# Generated by Django 5.2.6 on 2025-09-18 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='estimated_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Estimated time to complete the service'),
        ),
    ]
