# Generated by Django 5.2.6 on 2025-09-18 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_estimated_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='estimated_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Tempo estimado para concluir o serviço'),
        ),
    ]
