# Generated by Django 5.2.6 on 2025-09-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_estimated_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='complement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
