# Generated by Django 5.2.6 on 2025-09-18 20:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_userprofile_complement_userprofile_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('repair', 'Reparo'), ('assembly', 'Montagem'), ('plumbing', 'Encanamento'), ('electrical', 'Elétrica'), ('cleaning', 'Limpeza'), ('painting', 'Pintura'), ('other', 'Outros')], max_length=20)),
                ('estimated_price', models.DecimalField(decimal_places=2, help_text='Preço estimado do serviço', max_digits=10)),
                ('estimated_duration', models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Tempo estimado para concluir o serviço')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
