# Generated by Django 4.2.7 on 2025-10-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_order_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]