# Generated by Django 5.2.6 on 20251015 17:29

from django.db import migrations
from decimal import Decimal, InvalidOperation


def fix_decimal_values(apps, schema_editor):
    CustomService = apps.get_model('services', 'CustomService')
    
    # Fix invalid decimal values in estimated_price field
    for service in CustomService.objects.all():
        try:
            # Try to access the estimated_price to trigger conversion
            price = service.estimated_price
            if price is not None:
                # Convert to string and back to ensure it's valid
                Decimal(str(price))
        except (InvalidOperation, TypeError, ValueError):
            # If there's an error, set to a default value
            service.estimated_price = Decimal('0.00')
            service.save()


def reverse_fix_decimal_values(apps, schema_editor):
    # No reverse operation needed
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_message_is_ai_message_alter_message_sender'),
    ]

    operations = [
        migrations.RunPython(fix_decimal_values, reverse_fix_decimal_values),
    ]