# Generated by Django 5.2.6 on 2025-10-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customservice',
            name='category',
            field=models.CharField(choices=[('repair', 'Reparo'), ('assembly', 'Montagem'), ('plumbing', 'Encanamento'), ('electrical', 'Elétrica'), ('cleaning', 'Limpeza'), ('painting', 'Pintura'), ('carpentry', 'Marcenaria'), ('gardening', 'Jardinagem'), ('pest_control', 'Controle de Pragas'), ('air_conditioning', 'Ar Condicionado'), ('locksmith', 'Chaveiro'), ('moving', 'Mudanças'), ('other', 'Outros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('repair', 'Reparo'), ('assembly', 'Montagem'), ('plumbing', 'Encanamento'), ('electrical', 'Elétrica'), ('cleaning', 'Limpeza'), ('painting', 'Pintura'), ('carpentry', 'Marcenaria'), ('gardening', 'Jardinagem'), ('pest_control', 'Controle de Pragas'), ('air_conditioning', 'Ar Condicionado'), ('locksmith', 'Chaveiro'), ('moving', 'Mudanças'), ('other', 'Outros')], max_length=20),
        ),
    ]
