# Generated by Django 5.2.6 on 2025-10-23 10:00

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_userprofile_birth_date_userprofile_dark_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, help_text='Name of the field that was changed')),
                ('old_value', models.TextField(blank=True, help_text='Previous value of the field')),
                ('new_value', models.TextField(blank=True, help_text='New value of the field')),
                ('change_type', models.CharField(choices=[('update', 'Update'), ('create', 'Create'), ('delete', 'Delete')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, help_text='IP address of the user who made the change')),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the browser used to make the change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, help_text='User whose profile was changed')),
            ],
            options={
                'verbose_name': 'Profile Change',
                'verbose_name_plural': 'Profile Changes',
                'ordering': ['-created_at'],
            },
        ),
    ]