# Generated by Django 5.2.6 on 2025-11-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_servicerequestmodal'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestmodal',
            name='address_cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='servicerequestmodal',
            name='address_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicerequestmodal',
            name='address_complement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicerequestmodal',
            name='address_neighborhood',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicerequestmodal',
            name='address_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='servicerequestmodal',
            name='address_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='servicerequestmodal',
            name='address_street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='servicerequestmodal',
            name='contact_cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='servicerequestmodal',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('pix', 'PIX'), ('transferencia', 'Transferência')], max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequestmodal',
            name='payment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerequestmodal',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequestmodal',
            name='preferred_period',
            field=models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('flexivel', 'Flexível')], max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequestmodal',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequestmodal',
            name='schedule_notes',
            field=models.TextField(blank=True),
        ),
    ]
