# Generated by Django 5.2.6 on 2025-11-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_servicerequestmodal_address_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestmodal',
            name='card_installments',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='servicerequestmodal',
            name='card_type',
            field=models.CharField(blank=True, choices=[('debito', 'Débito'), ('credito', 'Crédito'), ('ambos', 'Ambos')], max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequestmodal',
            name='client_money_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequestmodal',
            name='needs_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequestmodal',
            name='pix_identifier',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
