# Generated by Django 5.2.6 on 2025-11-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_servicerequestmodal_card_installments_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
