# Generated by Django 5.2.6 on 2025-11-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_remove_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_category',
            field=models.CharField(blank=True, help_text='Categoria do serviço', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='service_description',
            field=models.TextField(blank=True, help_text='Descrição detalhada do serviço'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_name',
            field=models.CharField(blank=True, help_text='Nome do serviço solicitado', max_length=200),
        ),
    ]
