# Generated by Django 5.2.6 on 2025-11-05 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_add_service_details_to_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('service_id', models.IntegerField()),
                ('current_step', models.IntegerField(default=1)),
                ('step1_data', models.JSONField(blank=True, null=True)),
                ('step2_data', models.JSONField(blank=True, null=True)),
                ('step3_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Solicitação',
                'verbose_name_plural': 'Sessões de Solicitação',
                'ordering': ['-created_at'],
            },
        ),
    ]
