# Generated by Django 5.2.6 on 2025-11-06 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_servicerequestsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Biografia do profissional'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_hours',
            field=models.TextField(blank=True, help_text='Horário de funcionamento'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_name',
            field=models.CharField(blank=True, help_text='Nome da empresa/negócio', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='Certificações e qualificações'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ (se aplicável)', max_length=18),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='completed_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_years',
            field=models.IntegerField(default=0, help_text='Anos de experiência'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Disponível para novos trabalhos'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Conta premium'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Profissional verificado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='pt-br', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Perfil do LinkedIn'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Link do portfólio'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='response_time_hours',
            field=models.IntegerField(default=24, help_text='Tempo médio de resposta em horas'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='service_radius',
            field=models.IntegerField(default=10, help_text='Raio de atendimento em km'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialties',
            field=models.TextField(blank=True, help_text='Especialidades (separadas por vírgula)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='America/Sao_Paulo', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website_url',
            field=models.URLField(blank=True, help_text='Website pessoal'),
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do trabalho', max_length=200)),
                ('description', models.TextField(help_text='Descrição do trabalho realizado')),
                ('category', models.CharField(choices=[('repair', 'Reparo'), ('assembly', 'Montagem'), ('plumbing', 'Encanamento'), ('electrical', 'Elétrica'), ('cleaning', 'Limpeza'), ('painting', 'Pintura'), ('carpentry', 'Marcenaria'), ('gardening', 'Jardinagem'), ('pest_control', 'Controle de Pragas'), ('air_conditioning', 'Ar Condicionado'), ('locksmith', 'Chaveiro'), ('moving', 'Mudanças'), ('other', 'Outros')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('completion_date', models.DateField(help_text='Data de conclusão')),
                ('client_name', models.CharField(blank=True, help_text='Nome do cliente (opcional)', max_length=100)),
                ('project_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Destacar no perfil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completion_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('professional', 'weekday')},
            },
        ),
    ]
