# Generated by Django 5.2.6 on 2025-11-10 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_userprofile_bio_userprofile_business_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestmodal',
            name='client_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequestmodal',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequestmodal',
            name='provider_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='servicerequestmodal',
            index=models.Index(fields=['user', '-created_at'], name='services_se_user_id_38bfbe_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequestmodal',
            index=models.Index(fields=['provider', '-created_at'], name='services_se_provide_f97c40_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequestmodal',
            index=models.Index(fields=['status'], name='services_se_status_f01345_idx'),
        ),
    ]
