# Generated by Django 5.2.6 on 2025-11-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_servicerequestmodal_client_notified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('subject', models.CharField(choices=[('duvida', 'Dúvida'), ('suporte', 'Suporte Técnico'), ('sugestao', 'Sugestão'), ('reclamacao', 'Reclamação'), ('outro', 'Outro')], max_length=20, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('new', 'Nova'), ('read', 'Lida'), ('replied', 'Respondida'), ('archived', 'Arquivada')], default='new', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas do Administrador')),
            ],
            options={
                'verbose_name': 'Mensagem de Contato',
                'verbose_name_plural': 'Mensagens de Contato',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='services_co_created_3b1916_idx'), models.Index(fields=['status'], name='services_co_status_540031_idx')],
            },
        ),
    ]
