# Generated by Django 5.2.6 on 2025-11-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_add_search_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, help_text='User ID or IP address', max_length=100)),
                ('endpoint', models.CharField(help_text='API endpoint path', max_length=200)),
                ('request_count', models.IntegerField(default=0, help_text='Number of requests in this window')),
                ('limit', models.IntegerField(help_text='Rate limit for this identifier')),
                ('window_start', models.DateTimeField(db_index=True, help_text='Start of the rate limit window')),
                ('window_end', models.DateTimeField(help_text='End of the rate limit window')),
                ('exceeded', models.BooleanField(default=False, help_text='Whether the limit was exceeded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rate Limit Record',
                'verbose_name_plural': 'Rate Limit Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='customservice',
            name='services_cu_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='customservice',
            name='services_cu_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='customservice',
            name='services_cu_price_idx',
        ),
        migrations.RemoveIndex(
            model_name='customservice',
            name='services_cu_active_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='customservice',
            name='services_cu_cat_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='services_up_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='services_up_rating_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='services_up_city_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='services_up_state_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='services_up_verified_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='services_up_available_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='services_up_location_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='services_up_type_rating_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='services_up_type_avail_rating_idx',
        ),
        migrations.AddIndex(
            model_name='ratelimitrecord',
            index=models.Index(fields=['identifier', 'endpoint', 'window_start'], name='services_ra_identif_26d07f_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitrecord',
            index=models.Index(fields=['exceeded', '-created_at'], name='services_ra_exceede_0e6865_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitrecord',
            index=models.Index(fields=['-created_at'], name='services_ra_created_807548_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ratelimitrecord',
            unique_together={('identifier', 'endpoint', 'window_start')},
        ),
    ]
