# Generated by Django 5.2.6 on 2025-11-17 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_ratelimitrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, help_text='API endpoint path', max_length=200)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('status_code', models.IntegerField(db_index=True, help_text='HTTP status code')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the request was made')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the client')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('user', models.ForeignKey(blank=True, help_text='User who made the request', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Metric',
                'verbose_name_plural': 'API Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['endpoint', '-timestamp'], name='services_ap_endpoin_5dc72f_idx'), models.Index(fields=['status_code', '-timestamp'], name='services_ap_status__035700_idx'), models.Index(fields=['user', '-timestamp'], name='services_ap_user_id_56f306_idx'), models.Index(fields=['-response_time'], name='services_ap_respons_90f7f5_idx')],
            },
        ),
    ]
