# Generated by Django 5.2.6 on 2025-11-17 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_apimetric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('order_update', 'Atualização de Pedidos'), ('professional_approval', 'Aprovação de Profissionais'), ('service_update', 'Atualização de Serviços'), ('user_update', 'Atualização de Usuários'), ('bulk_delete', 'Exclusão em Lote'), ('custom', 'Operação Customizada')], help_text='Type of batch operation', max_length=50)),
                ('total_operations', models.IntegerField(help_text='Total number of operations in this batch')),
                ('completed_operations', models.IntegerField(default=0, help_text='Number of successfully completed operations')),
                ('failed_operations', models.IntegerField(default=0, help_text='Number of failed operations')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('partial', 'Parcialmente Concluído')], db_index=True, default='pending', help_text='Current status of the batch operation', max_length=20)),
                ('result_data', models.JSONField(blank=True, help_text='Detailed results for each operation in the batch', null=True)),
                ('error_details', models.JSONField(blank=True, help_text='Details of any errors that occurred', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the batch operation was created')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the batch operation started processing', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the batch operation completed', null=True)),
                ('user', models.ForeignKey(help_text='User who initiated the batch operation', on_delete=django.db.models.deletion.CASCADE, related_name='batch_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Operation',
                'verbose_name_plural': 'Batch Operations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='services_ba_user_id_0962d9_idx'), models.Index(fields=['status', '-created_at'], name='services_ba_status_804e86_idx'), models.Index(fields=['operation_type', '-created_at'], name='services_ba_operati_9942fd_idx')],
            },
        ),
    ]
