# Generated by Django 5.2.6 on 2025-11-19 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_batchoperation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the chat session', primary_key=True, serialize=False)),
                ('anonymous_id', models.CharField(blank=True, help_text='Identifier for anonymous users', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the session was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last activity in this session')),
                ('closed_at', models.DateTimeField(blank=True, help_text='When the session was closed', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the session is currently active')),
                ('context_data', models.JSONField(default=dict, help_text='Navigation context, user preferences, and session state')),
                ('user_type', models.CharField(choices=[('client', 'Cliente'), ('provider', 'Prestador'), ('anonymous', 'Anônimo')], default='anonymous', help_text='Type of user (client, provider, or anonymous)', max_length=20)),
                ('satisfaction_rating', models.IntegerField(blank=True, help_text='User satisfaction rating (1-5)', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User associated with this session (null for anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the message', primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Sophie'), ('system', 'Sistema')], help_text='Type of sender (user, assistant, or system)', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('metadata', models.JSONField(default=dict, help_text='Additional data: intent, confidence, links, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the message was created')),
                ('is_cached_response', models.BooleanField(default=False, help_text='Whether this response came from cache')),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Time taken to process and generate response (milliseconds)', null=True)),
                ('session', models.ForeignKey(help_text='Chat session this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='services.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('analytics_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the analytics record', primary_key=True, serialize=False)),
                ('total_messages', models.IntegerField(default=0, help_text='Total number of messages in the session')),
                ('user_messages', models.IntegerField(default=0, help_text='Number of messages from the user')),
                ('assistant_messages', models.IntegerField(default=0, help_text='Number of messages from Sophie')),
                ('average_response_time_ms', models.FloatField(blank=True, help_text='Average response time in milliseconds', null=True)),
                ('resolved', models.BooleanField(default=False, help_text="Whether the user's issue was resolved")),
                ('escalated_to_human', models.BooleanField(default=False, help_text='Whether the conversation was escalated to human support')),
                ('topics_discussed', models.JSONField(default=list, help_text='List of topics discussed in the session')),
                ('actions_taken', models.JSONField(default=list, help_text='Actions taken by user (links clicked, services viewed, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the analytics record was created')),
                ('session', models.OneToOneField(help_text='Chat session this analytics record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='services.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Analytics',
                'verbose_name_plural': 'Chat Analytics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseEntry',
            fields=[
                ('entry_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the knowledge base entry', primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('service', 'Serviço'), ('faq', 'FAQ'), ('navigation', 'Navegação'), ('policy', 'Política'), ('troubleshooting', 'Solução de Problemas')], db_index=True, help_text='Category of the knowledge base entry', max_length=50)),
                ('title', models.CharField(help_text='Title of the knowledge base entry', max_length=255)),
                ('content', models.TextField(help_text='Content of the knowledge base entry')),
                ('keywords', models.JSONField(default=list, help_text='Keywords for searching this entry')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata for the entry')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the entry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the entry was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the entry is active and searchable')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this entry has been used')),
                ('related_services', models.ManyToManyField(blank=True, help_text='Services related to this knowledge base entry', related_name='knowledge_entries', to='services.service')),
            ],
            options={
                'verbose_name': 'Knowledge Base Entry',
                'verbose_name_plural': 'Knowledge Base Entries',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-created_at'], name='services_ch_user_id_dfffa4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['is_active', '-updated_at'], name='services_ch_is_acti_95863f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='services_ch_session_419ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseentry',
            index=models.Index(fields=['category', 'is_active'], name='services_kn_categor_0e859b_idx'),
        ),
    ]
