# Generated by Django 5.2.6 on 2025-12-01 18:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_chatsession_chatmessage_chatanalytics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatanalytics',
            options={'verbose_name_plural': 'Chat Analytics'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='knowledgebaseentry',
            options={'ordering': ['-usage_count', '-updated_at'], 'verbose_name_plural': 'Knowledge Base Entries'},
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_messag_session_597c4e_idx',
            old_name='services_ch_session_419ac1_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='chat_sessio_user_id_c65971_idx',
            old_name='services_ch_user_id_dfffa4_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='chat_sessio_is_acti_f9768f_idx',
            old_name='services_ch_is_acti_95863f_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgebaseentry',
            new_name='knowledge_b_categor_6c6fcd_idx',
            old_name='services_kn_categor_0e859b_idx',
        ),
        migrations.AlterField(
            model_name='chatanalytics',
            name='actions_taken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chatanalytics',
            name='analytics_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatanalytics',
            name='assistant_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatanalytics',
            name='average_response_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatanalytics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatanalytics',
            name='escalated_to_human',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatanalytics',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatanalytics',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='services.chatsession'),
        ),
        migrations.AlterField(
            model_name='chatanalytics',
            name='topics_discussed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chatanalytics',
            name='total_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatanalytics',
            name='user_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_cached_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='processing_time_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_type',
            field=models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Sophie'), ('system', 'Sistema')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='services.chatsession'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='anonymous_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='context_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='satisfaction_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user_type',
            field=models.CharField(choices=[('client', 'Cliente'), ('provider', 'Prestador'), ('anonymous', 'Anônimo')], default='anonymous', max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='category',
            field=models.CharField(choices=[('service', 'Serviço'), ('faq', 'FAQ'), ('navigation', 'Navegação'), ('policy', 'Política'), ('troubleshooting', 'Solução de Problemas')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='entry_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='related_services',
            field=models.ManyToManyField(blank=True, related_name='knowledge_entries', to='services.service'),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='chatanalytics',
            table='chat_analytics',
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table='chat_messages',
        ),
        migrations.AlterModelTable(
            name='chatsession',
            table='chat_sessions',
        ),
        migrations.AlterModelTable(
            name='knowledgebaseentry',
            table='knowledge_base_entries',
        ),
    ]
