# Generated by Django 5.2.6 on 2025-12-02 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_alter_chatanalytics_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Cliente'), ('professional', 'Profissional'), ('admin', 'Administrador'), ('support', 'Suporte')], default='customer', max_length=20),
        ),
        migrations.CreateModel(
            name='SupportAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('department', models.CharField(choices=[('technical', 'Suporte Técnico'), ('billing', 'Financeiro'), ('general', 'Geral')], default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('max_concurrent_tickets', models.IntegerField(default=10, verbose_name='Máximo de tickets simultâneos')),
                ('total_tickets_handled', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('average_response_time_minutes', models.IntegerField(default=0, help_text='Tempo médio de resposta em minutos')),
                ('average_resolution_time_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Tempo médio de resolução em horas', max_digits=5)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agente de Suporte',
                'verbose_name_plural': 'Agentes de Suporte',
            },
        ),
        migrations.CreateModel(
            name='SupportKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('getting_started', 'Primeiros Passos'), ('account', 'Conta e Perfil'), ('services', 'Serviços'), ('payments', 'Pagamentos'), ('technical', 'Problemas Técnicos'), ('policies', 'Políticas'), ('faq', 'Perguntas Frequentes')], max_length=20, verbose_name='Categoria')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('summary', models.TextField(max_length=500, verbose_name='Resumo')),
                ('keywords', models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula', max_length=200)),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('view_count', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='Útil')),
                ('not_helpful_count', models.IntegerField(default=0, verbose_name='Não útil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artigo da Base de Conhecimento',
                'verbose_name_plural': 'Base de Conhecimento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('category', models.CharField(choices=[('technical', 'Problema Técnico'), ('account', 'Conta e Perfil'), ('payment', 'Pagamento'), ('service', 'Serviços'), ('complaint', 'Reclamação'), ('suggestion', 'Sugestão'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Categoria')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('in_progress', 'Em Andamento'), ('waiting_customer', 'Aguardando Cliente'), ('waiting_support', 'Aguardando Suporte'), ('resolved', 'Resolvido'), ('closed', 'Fechado')], db_index=True, default='open', max_length=20, verbose_name='Status')),
                ('attachment', models.FileField(blank=True, help_text='Arquivo anexo (screenshot, documento, etc)', null=True, upload_to='support_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fechado em')),
                ('customer_rating', models.IntegerField(blank=True, choices=[(1, '1 estrelas'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, '5 estrelas')], help_text='Avaliação do cliente (1-5)', null=True)),
                ('customer_feedback', models.TextField(blank=True, help_text='Feedback do cliente')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Agente de suporte responsável', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Cliente que abriu o ticket', on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Suporte',
                'verbose_name_plural': 'Tickets de Suporte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('message', 'Mensagem'), ('note', 'Nota Interna'), ('system', 'Sistema')], default='message', max_length=10, verbose_name='Tipo')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_message_attachments/', verbose_name='Anexo')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='services.supportticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Mensagem de Suporte',
                'verbose_name_plural': 'Mensagens de Suporte',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['customer', '-created_at'], name='services_su_custome_560073_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to', 'status'], name='services_su_assigne_7967b5_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', '-created_at'], name='services_su_status_5806ed_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['priority', '-created_at'], name='services_su_priorit_6e4637_idx'),
        ),
    ]
